# Generated by Django 4.2.1 on 2023-05-10 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_item_labels_alter_label_ui_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='ui_flag',
            field=models.CharField(choices=[('primary', 'primary'), ('secondary', 'secondary'), ('danger', 'danger'), ('success', 'success'), ('dark', 'dark')], max_length=100),
        ),
    ]
