# Generated by Django 4.2.1 on 2023-05-10 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_label_ui_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='ui_flag',
            field=models.CharField(choices=[('primary', 'blue'), ('secondary', 'grey'), ('danger', 'red'), ('success', 'green'), ('dark', 'black')], max_length=100),
        ),
    ]
