# Generated by Django 4.2.1 on 2023-05-10 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_label_ui_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='slug',
            field=models.SlugField(default='test-product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='labels',
            field=models.ManyToManyField(blank=True, to='core.label'),
        ),
    ]
